[package]
name = "bidding-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
k256 = { version = "=0.13.4", features = ["arithmetic", "serde", "expose-field", "std", "ecdsa"], default_features = false }
