[package]
name = "bank_server"
version = "0.1.0"
edition = "2021"

[lib]
name = "bank_server"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
k256 = { version = "0.13", features = ["ecdsa"] }
hex = "0.4"
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
pyo3-build-config = "0.18"